In [19]:
!pip install requests

Requirement already satisfied: requests in c:\users\shifa\anaconda3\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\shifa\anaconda3\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\shifa\anaconda3\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\shifa\anaconda3\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\shifa\anaconda3\lib\site-packages (from requests) (2025.11.12)

In [20]:
import requests

In [21]:
#api-request practise
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

In [22]:
res

In [23]:
json_data = res.json()

In [24]:
import pandas as pd
df = pd.json_normalize(json_data["data"])
df[["id", "Title", "ISBN"]]

    id          Title               ISBN
0    1         Carrie  978-0-385-08695-0
1    2    Salem's Lot  978-0-385-00751-1
2    3    The Shining  978-0-385-12167-5
3    4           Rage  978-0-451-07645-8
4    5      The Stand  978-0-385-12168-2
..  ..            ...                ...
58  59   The Outsider  978-1-50118-098-9
59  60      Elevation  978-1-98210-231-9
60  61  The Institute  978-1-98211-056-7
61  62          Later  978-1-78909-649-1
62  63  Billy Summers  978-1-982-17361-6

[63 rows x 3 columns]

In [25]:
#api-request mini-activity
URL = "https://whiskyhunter.net/api/?format=openapi"
resp = requests.get(URL)
resp

In [26]:
json_data = resp.json()

In [27]:
json_data

{'swagger': '2.0',
 'info': {'title': 'Whisky Hunter API',
  'description': 'All trading volumes and winning bids are stated in <strong>£ (GBP)</strong>. Regardless of the base currency of the auction. \nThe volume calculation for auctions or distilleries includes only the lots actually sold (excluding those that have not reached the reserve price)',
  'termsOfService': '/privacy-policy/',
  'version': 'v1'},
 'host': 'whiskyhunter.net',
 'schemes': ['https'],
 'basePath': '/api',
 'consumes': ['application/json'],
 'produces': ['application/json'],
 'securityDefinitions': {'Basic': {'type': 'basic'}},
 'security': [{'Basic': []}],
 'paths': {'/auction_data/{slug}/': {'get': {'operationId': 'auction_data_read',
    'description': 'List only aggregated data for online auction {slug}. Example: /api/auction_data/catawiki/',
    'parameters': [],
    'responses': {'200': {'description': ''}},
    'tags': ['auction_data']},
   'parameters': [{'name': 'slug',
     'in': 'path',
     'required': True,
     'type': 'string'}]},
  '/auctions_data/': {'get': {'operationId': 'auctions_data_list',
    'description': 'List all online auctions aggregated data.',
    'parameters': [],
    'responses': {'200': {'description': ''}},
    'tags': ['auctions_data']},
   'parameters': []},
  '/auctions_info': {'get': {'operationId': 'auctions_info_list',
    'description': 'List all online auctions main information.',
    'parameters': [],
    'responses': {'200': {'description': ''}},
    'tags': ['auctions_info']},
   'parameters': []},
  '/distilleries_info/': {'get': {'operationId': 'distilleries_info_list',
    'description': 'List all distilleries main information.',
    'parameters': [],
    'responses': {'200': {'description': ''}},
    'tags': ['distilleries_info']},
   'parameters': []},
  '/distillery_data/{slug}/': {'get': {'operationId': 'distillery_data_read',
    'description': 'List data for distillery {slug}. Example: /api/distillery_data/ardbeg/',
    'parameters': [],
    'responses': {'200': {'description': ''}},
    'tags': ['distillery_data']},
   'parameters': [{'name': 'slug',
     'in': 'path',
     'required': True,
     'type': 'string'}]}},
 'definitions': {}}

In [28]:
df = pd.json_normalize(json_data)
df

,swagger,host,schemes,basePath,consumes,produces,security,info.title,info.description,info.termsOfService,...,paths./distilleries_info/.get.parameters,paths./distilleries_info/.get.responses.200.description,paths./distilleries_info/.get.tags,paths./distilleries_info/.parameters,paths./distillery_data/{slug}/.get.operationId,paths./distillery_data/{slug}/.get.description,paths./distillery_data/{slug}/.get.parameters,paths./distillery_data/{slug}/.get.responses.200.description,paths./distillery_data/{slug}/.get.tags,paths./distillery_data/{slug}/.parameters
0,2.0,whiskyhunter.net,[https],/api,[application/json],[application/json],[{'Basic': []}],Whisky Hunter API,All trading volumes and winning bids are state...,/privacy-policy/,...,[],,[distilleries_info],[],distillery_data_read,List data for distillery {slug}. Example: /api...,[],,[distillery_data],"[{'name': 'slug', 'in': 'path', 'required': Tr..."

In [29]:
#web-scraping of a simple website
import requests
URL = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)
res

In [30]:
if res.status_code == 200 :
    print(res.headers)

with open ("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Sat, 07 Mar 2026 02:52:52 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=o6OsfF7AkSAgFkdc1NSFr3q35Ctzh9H8R3gRni%2BGj5k%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1772851972"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=o6OsfF7AkSAgFkdc1NSFr3q35Ctzh9H8R3gRni%2BGj5k%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1772851972"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9d864e76fbdb9fbc-SIN', 'alt-svc': 'h3=":443"; ma=86400'}

In [31]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\shifa\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\shifa\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\shifa\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)

In [32]:
from bs4 import BeautifulSoup

with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [33]:
all_h3 = soup.find_all("h3")
all_countries = []
for h3 in all_h3:
    names = h3.get_text(strip=True)
    # print(h3.find_parent("div")["class"])
    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    all_countries.append([names, population])

In [34]:
import pandas as pd
df = pd.DataFrame(all_countries, columns = ["Name", "Population"])

In [35]:
df.to_csv("cleaned_data/data.csv", index = False)

In [45]:
#web-scraping activity

URL = "http://quotes.toscrape.com/"
res = requests.get(URL)
res

In [42]:
with open("scraped_data/data2.html", "w", encoding = "utf-8") as f:
    f.write(res.text)

In [44]:
with open("scraped_data/data2.html", "r", encoding="utf-8") as f:
    html_content2 = f.read()

soup2 = BeautifulSoup(html_content2, "lxml")