In [30]:
import requests

In [31]:
#api-request 
URL = "https://stephen-king-api.onrender.com/api/books"
res = requests.get(URL)

In [32]:
res

In [33]:
json_data = res.json()

In [34]:
import pandas as pd
df = pd.json_normalize(json_data["data"])
df[["id", "Title", "ISBN"]]

    id          Title               ISBN
0    1         Carrie  978-0-385-08695-0
1    2    Salem's Lot  978-0-385-00751-1
2    3    The Shining  978-0-385-12167-5
3    4           Rage  978-0-451-07645-8
4    5      The Stand  978-0-385-12168-2
..  ..            ...                ...
58  59   The Outsider  978-1-50118-098-9
59  60      Elevation  978-1-98210-231-9
60  61  The Institute  978-1-98211-056-7
61  62          Later  978-1-78909-649-1
62  63  Billy Summers  978-1-982-17361-6

[63 rows x 3 columns]

In [35]:
URL = "https://whiskyhunter.net/api/?format=openapi"
resp = requests.get(URL)
resp

In [36]:
json_data = resp.json()

In [37]:
df = pd.json_normalize(json_data)
df

,swagger,host,schemes,basePath,consumes,produces,security,info.title,info.description,info.termsOfService,...,paths./distilleries_info/.get.parameters,paths./distilleries_info/.get.responses.200.description,paths./distilleries_info/.get.tags,paths./distilleries_info/.parameters,paths./distillery_data/{slug}/.get.operationId,paths./distillery_data/{slug}/.get.description,paths./distillery_data/{slug}/.get.parameters,paths./distillery_data/{slug}/.get.responses.200.description,paths./distillery_data/{slug}/.get.tags,paths./distillery_data/{slug}/.parameters
0,2.0,whiskyhunter.net,[https],/api,[application/json],[application/json],[{'Basic': []}],Whisky Hunter API,All trading volumes and winning bids are state...,/privacy-policy/,...,[],,[distilleries_info],[],distillery_data_read,List data for distillery {slug}. Example: /api...,[],,[distillery_data],"[{'name': 'slug', 'in': 'path', 'required': Tr..."

In [38]:
#web-scraping 

URL = "https://www.scrapethissite.com/pages/simple/"
res = requests.get(URL)
res

In [39]:
if res.status_code == 200 :
    print(res.headers)

with open ("scraped_data/data1.html", "w", encoding="utf-8") as f:
    f.write(res.text)

{'Date': 'Sat, 07 Mar 2026 07:42:25 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'Report-To': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=swP5oNx%2FJudYI0qlTvyJ%2BZYVyVaS3HyNLOCptC9eE8o%3D\\u0026sid=67ff5de4-ad2b-4112-9289-cf96be89efed\\u0026ts=1772869345"}],"max_age":3600}', 'Reporting-Endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=swP5oNx%2FJudYI0qlTvyJ%2BZYVyVaS3HyNLOCptC9eE8o%3D&sid=67ff5de4-ad2b-4112-9289-cf96be89efed&ts=1772869345"', 'Server': 'cloudflare', 'Via': '1.1 heroku-router', 'cf-cache-status': 'DYNAMIC', 'Content-Encoding': 'zstd', 'CF-RAY': '9d87f69c4ceb8b19-DEL', 'alt-svc': 'h3=":443"; ma=86400'}

In [40]:
from bs4 import BeautifulSoup

with open("scraped_data/data1.html", "r") as f:
    html_content = f.read()

soup = BeautifulSoup(html_content, "lxml")

In [41]:
all_h3 = soup.find_all("h3")
all_countries = []
for h3 in all_h3:
    names = h3.get_text(strip=True)
    # print(h3.find_parent("div")["class"])
    population = h3.find_next("div").select("span.country-population")[0].get_text(strip=True)
    all_countries.append([names, population])

In [42]:
import pandas as pd
df = pd.DataFrame(all_countries, columns = ["Name", "Population"])

In [43]:
df.to_csv("cleaned_data/data.csv", index = False)